### ISSUE TITLE
LAMMPS setup for RIV calculation according to Mayr et al.

### ISSUE THREAD

**Issue by AlexanderToifl** [AlexanderToifl/RIV#2]
-> Is an equilibration step after quenching step necessary?

-> How to set up a biaxial deformation and determine eps_xx and eps_yy?

-> When are the recoils added? Periodicity?

-> Do the recoils only require setting the velocity of one atom? If the velocities of multiple atoms have to be changed, how to implement that in LAMMPS?

-> How to set the velocity after the recoil as function of recoil energy? The velocity command presented in AT branch requires three concrete vx vy vz values.

**Comment by chri3005** [comment]
-> I have not found anything about a equlibration step after quenching. I believe that we are in an Equilibrium already due to the use of the Thermostat. 
-> Biaxial Deformation using fix deform and try different deformations with values for instance shown in the a-Ge paper - interestingly they seem to also have applied biaxial stresses and measured the deformations as we suggested last time, resulting in a linear relation. Also RIV was extracted that way.
We also should consider to use Tersoff potentials, as they always have seemed to generate more realistic results.
-> I would say the recoils are added after the deform has equilibrated. That give our sigma0.
-> We should start with 1 Atom
-> worst case we generate those values via python random numbers. Energy gives maximum absolute velocity = maximum velocity for 1st component - random #for 1st component - difference is max. vel. for 2nd component and so on

**Comment by AlexanderToifl** [comment]
-> Let's assume that no equilibration is necessary.
-> After deformation we look at changes of stress tensor components. If those are more or less constant we can add the recoils.
-> Your velocity algorithm is straightforward, it should be possible to implement that purely in LAMMPS as well.

Solved issues
-> Biaxial deformation is possible by using two subsequent uniaxial deformations (x and y direction).  

-> Stress monitoring 
(See AT branch)

**Comment by AlexanderToifl** [comment]
Once we find a way to periodically add recoils and elegantly implement the velocity algorithms within LAMMPS we can close this issue.

The next commit in master should provide a separate amorphization script, the biaxial  deformation and a few incorporated recoils.

**Comment by chri3005** [comment]
One issue with the periodical insertion of recoils is that a new group needs to be defined with the current algorithm for every atom, that should be replaced. That would limit our maximum recoils to 32, as no more groups can be defined according to the manual.

Also we need to implement thermostat and fix boundaries as we did with the sputter - project, to prevent the temperature rising unrealistically...

**Comment by AlexanderToifl** [comment]
Thermostat and fix velocity added, we can close the issue.
